Tracker:AddLocations("locations/Challenges.json")
Tracker:AddLocations("locations/Entrance Plaza.json")
Tracker:AddLocations("locations/Food and Fresca.json")
Tracker:AddLocations("locations/Leisure Park.json")
Tracker:AddLocations("locations/Levels.json")
Tracker:AddLocations("locations/Main Scoops.json")
Tracker:AddLocations("locations/Maintenance Tunnels.json")
Tracker:AddLocations("locations/North Plaza.json")
Tracker:AddLocations("locations/Paradise Plaza.json")
Tracker:AddLocations("locations/Wonderland Plaza.json")
Tracker:AddLocations("locations/Overworld.json")
